<a href="https://colab.research.google.com/github/dorahs71/ml-course/blob/main/mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

講義如果寫(tensorflow 1.x)

from keras...
全部改成(tensorflow 2.x)

from tensorflow.keras

In [1]:
from tensorflow.keras.datasets import mnist
# ((訓練圖片, 答案), (測試圖片, 答案))
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [2]:
x_train[0] # 共有 28 個像素，代表以下顯示的「5」圖片

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170,
        253, 253, 253, 253, 253, 225, 172, 253, 242, 195,  64,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  49, 238, 253, 253, 253, 253,
        253, 253, 253, 253, 251,  93,  82,  82,  56,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  18, 219, 253, 253, 253, 253,
        253, 198, 182, 247, 241,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  80, 156, 107, 253, 253,
        205,  11,   0,  43, 154,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14,   1, 154, 253,
         90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 139, 253,
        190,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11, 190,
        253,  70,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  35,
        241, 225, 160, 108,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         81, 240, 253, 253, 119,  25,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  45, 186, 253, 253, 150,  27,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  16,  93, 252, 253, 187,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 249, 253, 249,  64,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  46, 130, 183, 253, 253, 207,   2,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  39,
        148, 229, 253, 253, 253, 250, 182,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  24, 114, 221,
        253, 253, 253, 253, 201,  78,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  23,  66, 213, 253, 253,
        253, 253, 198,  81,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  18, 171, 219, 253, 253, 253, 253,
        195,  80,   9,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,  55, 172, 226, 253, 253, 253, 253, 244, 133,
         11,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 136, 253, 25

In [3]:
#灰階圖片 0 代表黑色, 255 代表白色
import pandas as pd

pd.DataFrame(x_train[0])

0   1   2   3    4    5    6    7    8    9   ...   18   19   20   21  \
0    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0   
1    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0   
2    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0   
3    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0   
4    0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0   
5    0   0   0   0    0    0    0    0    0    0  ...  175   26  166  255   
6    0   0   0   0    0    0    0    0   30   36  ...  225  172  253  242   
7    0   0   0   0    0    0    0   49  238  253  ...   93   82   82   56   
8    0   0   0   0    0    0    0   18  219  253  ...    0    0    0    0   
9    0   0   0   0    0    0    0    0   80  156  ...    0    0    0    0   
10   0   0   0   0    0    0    0    0    0   14  ...    0    0    0    0   
11   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0   
12   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0   
13   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0   
14   0   0   0   0    0    0    0    0    0    0  ...   25    0    0    0   
15   0   0   0   0    0    0    0    0    0    0  ...  150   27    0    0   
16   0   0   0   0    0    0    0    0    0    0  ...  253  187    0    0   
17   0   0   0   0    0    0    0    0    0    0  ...  253  249   64    0   
18   0   0   0   0    0    0    0    0    0    0  ...  253  207    2    0   
19   0   0   0   0    0    0    0    0    0    0  ...  250  182    0    0   
20   0   0   0   0    0    0    0    0    0    0  ...   78    0    0    0   
21   0   0   0   0    0    0    0    0   23   66  ...    0    0    0    0   
22   0   0   0   0    0    0   18  171  219  253  ...    0    0    0    0   
23   0   0   0   0   55  172  226  253  253  253  ...    0    0    0    0   
24   0   0   0   0  136  253  253  253  212  135  ...    0    0    0    0   
25   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0   
26   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0   
27   0   0   0   0    0    0    0    0    0    0  ...    0    0    0    0   

     22   23  24  25  26  27  
0     0    0   0   0   0   0  
1     0    0   0   0   0   0  
2     0    0   0   0   0   0  
3     0    0   0   0   0   0  
4     0    0   0   0   0   0  
5   247  127   0   0   0   0  
6   195   64   0   0   0   0  
7    39    0   0   0   0   0  
8     0    0   0   0   0   0  
9     0    0   0   0   0   0  
10    0    0   0   0   0   0  
11    0    0   0   0   0   0  
12    0    0   0   0   0   0  
13    0    0   0   0   0   0  
14    0    0   0   0   0   0  
15    0    0   0   0   0   0  
16    0    0   0   0   0   0  
17    0    0   0   0   0   0  
18    0    0   0   0   0   0  
19    0    0   0   0   0   0  
20    0    0   0   0   0   0  
21    0    0   0   0   0   0  
22    0    0   0   0   0   0  
23    0    0   0   0   0   0  
24    0    0   0   0   0   0  
25    0    0   0   0   0   0  
26    0    0   0   0   0   0  
27    0    0   0   0   0   0  

[28 rows x 28 columns]

In [4]:
# model 有兩種方式 Sequential(堆疊) Model(複雜)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense #全連接層(fully-connected)
# https://keras.io/api/layers/core_layers/dense/

layers = [
    # 784 * 64 + 64(bias)
    Dense(64, activation="sigmoid", input_dim=784), #784 變 64 再變 10
    # 標準化(加起來=1) 的就叫做 softmax
    # 係數 64 * 10 + 10(bias)
    Dense(10, activation="sigmoid")
    # 之所以是 10 層是因為，圖片中顯示的是 0 ~ 9 的阿拉伯數字，所以總共有 10 個可能性，若圖片是 5 ，則
    # 5 的判斷值為 1，其餘為 0 => [0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ]，加總起來一行就簡化為 1
    # 超參數 - 隨便選的參數，反正結果好就好了，如果發現結果很爛就再換
]

model = Sequential(layers)

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                50240     
                                                                 
 dense_1 (Dense)             (None, 10)                650       
                                                                 
Total params: 50890 (198.79 KB)
Trainable params: 50890 (198.79 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [5]:
# model.compile(loss="mse", metrics=["accuracy"])

from tensorflow.keras.losses import CategoricalCrossentropy
model.compile(loss=CategoricalCrossentropy(), metrics=["accuracy"]) #loss 的選擇是為了更快收斂模型(減少 epochs)

In [6]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [7]:
from tensorflow.keras.utils import to_categorical

y_train_onehot = to_categorical(y_train)
y_test_onehot = to_categorical(y_test)

print(y_train[0])
print(y_train_onehot[0])

5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [8]:
# 其實係數不是完全隨機，他是在某個範圍做隨機，其實變相要求你的輸入應該要落在某個範圍
# tensorflow 希望你的輸入落在 0~1 或者 -1~1

x_train_scaled = x_train.reshape(60000, 784) / 255.0 #也可以寫成 x_train.reshape(-1, 784)
x_test_scaled = x_test.reshape(10000, 784) / 255.0

在這段代碼中，`/ 255.0` 的操作是對像素值進行標準化。這是因為圖像數據通常以 0 到 255 之間的整數表示每個像素的灰度值或 RGB 值。對數據進行標準化的原因包括以下幾點：

1. **統一數據範圍**：
   - 將像素值範圍從 0-255 轉換到 0-1，可以統一數據範圍，使得所有像素值在相同的尺度上，這有助於提高模型的訓練效果。

2. **加快收斂速度**：
   - 在訓練神經網絡時，標準化數據可以加快梯度下降算法的收斂速度，從而加快訓練過程。

3. **穩定數值計算**：
   - 將數據縮放到 0-1 範圍內，可以避免大數值計算引起的數值不穩定性，從而提高計算的穩定性和模型的性能。

具體來說，這段代碼的每一步解釋如下：

```python
x_train_scaled = x_train.reshape(60000, 784) / 255.0  # 也可以寫成 x_train.reshape(-1, 784)
x_test_scaled = x_test.reshape(10000, 784) / 255.0
```

1. **`reshape` 操作**：
   - `x_train.reshape(60000, 784)` 將原始形狀為 `(60000, 28, 28)` 的 `x_train` 數據集重新整形為 `(60000, 784)`，即將每張 28x28 的圖像展平為一個 784 維的向量。
   - `x_train.reshape(-1, 784)` 是一個簡便寫法，其中 `-1` 會自動計算出所需的行數，這裡會得到相同的結果。

2. **`/ 255.0` 操作**：
   - 將每個像素值除以 255，將像素值從原始的 0-255 範圍縮放到 0-1 範圍。這樣做的目的是進行數據標準化。

這樣的標準化對於訓練神經網絡或其他機器學習模型是很有幫助的，因為它可以讓模型更快更穩定地收斂，提高預測精度。

Hope: 跟正確答案距離遠的時候，走快一點(節省時間)
      跟正確答案距離近的時候，走慢一點(不要錯過)

      走得速度，就代表斜率(負號)，所以走得速度快就代表斜率比較大(負號)，其實離很近的話斜率會比較小
      MSE 的算法是沒有問題的，但他很費時間，因為他沒滿足當距離遠時，斜率可以比較大

沒做任何改動： 60 epochs

將 MSE 改成 Cross Entropy ： 30 epochs
MSE 不是不行，但就是太慢了

在分類問題上面，基本上都是用 Cross Entropy ，因為斜率下降比較快

[Keras Callback API](https://keras.io/api/callbacks/)

- ModelCheckpoint (參數：save_best_only: 只存 val_loss 最好的那次）

- EarlyStopping (參數：patience - 五次沒進步，就自動停下來，restore_best_weights - 會回傳最好的一次結果)

In [10]:
# batch_size: 看了多少筆才更新一次模型參數 (100 是老師自己選的)
# epochs: 整份資料(60000筆)要看幾 round
# 究竟是幾 round 咧？ 我們不會無限訓練下去(當然loss 會越來越小) -> 過擬和
# -> 只看 validation_loss 來決定到底要訓練幾個 epochs，不看 val_accuracy，因為可能賽對
# 跟機器學習一樣，要準備一份電腦沒看過的，來檢視現在的擬和程度
# batch=100, vali=0.1, 1 個epoch 做了幾次模型更新：54000/100 = 540 => 總共做了 540 次模型更新
# verbose: 印 log 的程度, 0(quiet), 1(bar), 2(沒有bar)

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
callbacks = [
    EarlyStopping(patience=5, restore_best_weights=True),
    ModelCheckpoint("mnist.h5", save_best_only=True)
]

model.fit(x_train_scaled,
          y_train_onehot,
          batch_size=100,
          epochs=200, #因為加了 callback，所以可以大方給多點次數，反正會提前停止
          validation_split=0.1,
          verbose=2,
          callbacks=callbacks)

Epoch 1/200
540/540 - 4s - loss: 0.6554 - accuracy: 0.8526 - val_loss: 0.2821 - val_accuracy: 0.9255 - 4s/epoch - 7ms/step
Epoch 2/200


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


540/540 - 3s - loss: 0.2915 - accuracy: 0.9181 - val_loss: 0.2108 - val_accuracy: 0.9422 - 3s/epoch - 6ms/step
Epoch 3/200
540/540 - 3s - loss: 0.2357 - accuracy: 0.9320 - val_loss: 0.1782 - val_accuracy: 0.9517 - 3s/epoch - 5ms/step
Epoch 4/200
540/540 - 2s - loss: 0.2031 - accuracy: 0.9412 - val_loss: 0.1588 - val_accuracy: 0.9592 - 2s/epoch - 4ms/step
Epoch 5/200
540/540 - 2s - loss: 0.1792 - accuracy: 0.9481 - val_loss: 0.1432 - val_accuracy: 0.9623 - 2s/epoch - 4ms/step
Epoch 6/200
540/540 - 2s - loss: 0.1606 - accuracy: 0.9535 - val_loss: 0.1320 - val_accuracy: 0.9648 - 2s/epoch - 4ms/step
Epoch 7/200
540/540 - 2s - loss: 0.1454 - accuracy: 0.9576 - val_loss: 0.1226 - val_accuracy: 0.9670 - 2s/epoch - 4ms/step
Epoch 8/200
540/540 - 3s - loss: 0.1329 - accuracy: 0.9612 - val_loss: 0.1154 - val_accuracy: 0.9683 - 3s/epoch - 5ms/step
Epoch 9/200
540/540 - 3s - loss: 0.1222 - accuracy: 0.9645 - val_loss: 0.1119 - val_accuracy: 0.9682 - 3s/epoch - 5ms/step
Epoch 10/200
540/540 - 2s - 

In [11]:
# Demo argmax(之前的idxmax)
# axis=0 : 直行最大值; axis=1 : 橫列最大值;
import numpy as np

np.array([
    [1,2],
    [3,4],
    [5,6]
]).argmax(axis=0)

# output: [2,2] => 第一個直行的二號位最大， 第二個直行的二號位最大

np.array([
    [1,2],
    [3,4],
    [5,6]
]).argmax(axis=1)

# output: [1,1,1] => 第一個橫列的一號位最大， 第二個橫列的一號位最大, 第三個橫列的一號位最大

array([1, 1, 1])

In [12]:
model.evaluate(x_test_scaled, y_test_onehot)

313/313 [==============================] - 1s 2ms/step - loss: 0.0837 - accuracy: 0.9753


[0.08368676900863647, 0.9753000140190125]

In [13]:
pre = model.predict(x_test_scaled).argmax(axis=1)
pre
#accuracy_score()

313/313 [==============================] - 1s 2ms/step


array([7, 2, 1, ..., 4, 5, 6])